sensor:
  - platform: rest
    name: Coopernico Prices
    unique_id: coopernico_prices
    resource: http://coopernico.home-assistant.live/egetprices.php
    scan_interval: 3600
    verify_ssl: false
    unit_of_measurement: "EUR/kWh"
    params:
      ciclo:
        dia
      contador:
        bi
    value_template: >
        {{value_json.current_price}}
    json_attributes:
      - Prices
      - current_price
